// Forward Flow Findings — English
//
// Mirror of notes/forward-flow-findings.md as structured data, so the
// findings can render as cards inside the Forward Flow tab.
//
// Forward Flow detects things the broader system can't yet handle.
// Each entry is a gap surfaced by Forward Flow that needs to be addressed
// elsewhere in the codebase.

export const FORWARD_FLOW_FINDINGS = [
  {
    id:         1,
    title:      'No proper_noun atom in ATOMS',
    status:     'open',
    priority:   'important',
    surfacedBy: 'Typing "John" in Forward Flow.',
    missing:    'The 36 atoms in src/grammarAtoms.en.js include `noun` but no `proper_noun`. Capitalized names get classified as plain `noun` (or stay uncategorized) elsewhere.',
    workaround: 'Forward Flow uses a capitalization heuristic in src/subjectShapeDetector.js.',
    fix:        'Add `proper_noun` atom to grammarAtoms.en.js. Update L1 enrichment to classify capitalized name-like words.',
  },
  {
    id:         2,
    title:      'No morphology lookup for inflected verb forms',
    status:     'open',
    priority:   'important',
    surfacedBy: 'Typing "I gave him a book" — Forward Flow can\'t match `give` because "gave" isn\'t the base form.',
    missing:    'A surface-form → base-form lookup the macro layer can consult. formsMap.js exists but isn\'t wired to Forward Flow\'s verb match.',
    workaround: 'None. Inflected verb forms simply don\'t match argument structures yet.',
    fix:        'Wire formsMap.js into the verb-match step in GrammarBreakerForwardFlowTab.jsx.',
  },
  {
    id:         3,
    title:      'Common adjectives/nouns aren\'t reliably classified without L1 enrichment',
    status:     'open',
    priority:   'can wait',
    surfacedBy: 'Typing "the happy dog" before adjectives are L1-enriched — the detector couldn\'t classify "happy" as adjective.',
    missing:    'L1 enrichment hasn\'t run for many seed words. wordRegistry returns no category for unenriched words.',
    workaround: 'subjectShapeDetector.js hardcodes a small list of common adjectives and nouns as fallback.',
    fix:        'Run WordPipeline UI to L1-enrich the seed. Then the detector\'s wordRegistry-lookup path works and the hardcoded fallback can shrink.',
  },
  {
    id:         4,
    title:      'Auxiliary inflections aren\'t linked to base verbs',
    status:     'open',
    priority:   'can wait',
    surfacedBy: 'Building yes/no question detection — needed to recognize "is", "am", "are", etc. as exception openers.',
    missing:    'These are inflected forms of `be`, `have`, `do`. Forward Flow lists them as standalone strings in EXCEPTION_OPENERS.',
    workaround: 'Hardcoded list.',
    fix:        'Same as #2 — wire formsMap. Then derive the auxiliary set from be.forms ∪ have.forms ∪ do.forms.',
  },
  {
    id:         5,
    title:      'No `quantifier` atom or category',
    status:     'open',
    priority:   'important',
    surfacedBy: 'Building Subject shape detection for "some people", "every child", etc.',
    missing:    'Quantifiers (some, every, each, all, no, any, many, few, several, most) aren\'t in ATOMS as a category.',
    workaround: 'Hardcoded in subjectShapeDetector.js.',
    fix:        'Add `quantifier` atom to grammarAtoms.en.js and L1-enrich the closed-class quantifier words.',
  },
  {
    id:         6,
    title:      'No `interjection` / `discourse_marker` atom',
    status:     'open',
    priority:   'can wait',
    surfacedBy: 'Building Minor sentence / interjection exception type — "Hello", "Sorry", "Thanks", "Wow".',
    missing:    'Interjections and discourse markers aren\'t a recognized atom category.',
    workaround: 'Hardcoded set in GrammarBreakerForwardFlowTab.jsx.',
    fix:        'Either add an `interjection` atom (small closed class) OR treat minor sentences as a marked construction.',
  },
  {
    id:         7,
    title:      'Article agreement (A/An) not enforced anywhere else',
    status:     'open',
    priority:   'can wait',
    surfacedBy: 'Typing "a apple" — Forward Flow warns; nothing else does.',
    missing:    'A general agreement-checking layer for "a apple", "an dog", plural/tense agreement etc.',
    workaround: 'subjectShapeDetector.js `checkArticleAgreement` does a letter-based check.',
    fix:        'Open question — agreement checking is its own layer. Could be a small validation module that the macro layer invokes.',
  },
  {
    id:         8,
    title:      'No distinction between bare nouns and other Subject shapes',
    status:     'resolved',
    priority:   '—',
    surfacedBy: 'Designing the Subject shapes catalog. Chat\'s review.',
    missing:    'Bare nouns as Subjects (mass nouns, generic plurals) didn\'t fit any of the original 8 shapes.',
    workaround: 'Now resolved.',
    fix:        'Added bare_noun as the 9th Subject shape; detector handles single-token nouns and adj+noun without determiner.',
  },
  {
    id:         9,
    title:      'Subordinate-clause-initial openings not detected',
    status:     'open',
    priority:   'can wait',
    surfacedBy: 'Chat\'s review of the exception bucket — "If you go", "When she arrived", "Because he was tired".',
    missing:    'Sentences opening with a subordinator (if, when, because, although, since, before, after, while, unless, until).',
    workaround: 'None — currently routes to fundamental lane and fails to match any Subject shape.',
    fix:        'Add a new exception lane (e.g. `subordinate_fronted`). Architecture supports adding it without restructuring.',
  },
  {
    id:         10,
    title:      'Fronted topic / object not detected',
    status:     'open',
    priority:   'can wait',
    surfacedBy: 'Chat\'s review — "This book, I loved", "Coffee, I don\'t drink".',
    missing:    'Sentences where a non-subject element is fronted to position 0. The first word looks like a Subject NP but the comma signals it\'s a fronted topic.',
    workaround: 'None.',
    fix:        'Add a new exception lane (e.g. `topic_fronted`) detected by NP + comma pattern.',
  },
  {
    id:         11,
    title:      'Discourse-linker openings not detected',
    status:     'open',
    priority:   'can wait',
    surfacedBy: 'Chat\'s review — "And then he left", "But I stayed", "However, she disagreed", "So we left".',
    missing:    'Sentences opening with a discourse linker (and, but, however, so, therefore, moreover, furthermore, nevertheless).',
    workaround: 'None.',
    fix:        'Two architectural options: (a) new exception lane, or (b) discourse-prefix stripping pre-step before dispatch.',
  },
  {
    id:         12,
    title:      'Dummy insertion lumps three different constructions',
    status:     'open',
    priority:   'important',
    surfacedBy: 'Chat\'s review of the catalog. Currently `dummy_insertion` covers existential there + dummy it + cleft it.',
    missing:    'Internal branching of the dummy insertion category. Phase 3a detects only the "there" branch.',
    workaround: 'Catalog entry marks detection as "partial".',
    fix:        'Either split into 3 separate exception entries, OR keep as one detection card with internal sub-types.',
  },
]
