// Canonical L2 field list — single source of truth for which fields the L2
// enricher prompt populates on resolved word records.
//
// Patterns declare their dependencies via `consumesL2Fields: [...]`. The
// pattern-L2 wiring sanity check (see grammarBreakerPatterns.js module load)
// verifies each declared field is in this list. When you add a new field to
// the L2 enricher prompt (vite-plugins/wordEnricher.js), add it here too.
//
// Mirrors fields generated by the prompt and exposed via wordRegistry.js
// (getResolvedWord). Keep in sync.

export const L2_FIELDS = [
  // Universal
  'colloquial',
  'lemmaFamily',
  'derivedForms',

  // Noun-specific
  'countability',
  'properNoun',
  'concreteness',
  'animate',

  // Verb-specific
  'transitivity',
  'verbAspectClass',
  'commonCollocations',

  // Modifier-specific
  'adjectivePosition',
  'adverbType',
  'numeralType',

  // Pronoun (and applicable noun) features
  'person',
  'number',
  'gender',

  // Schema metadata
  'cefrLevel',
  'subLevel',
  'frequency',
  'forms',
  'grammaticalAtom',
  'alternateAtoms',
]

export const L2_FIELDS_SET = new Set(L2_FIELDS)
